### ISSUE TITLE
作者还会做Forge高版本的吗

### ISSUE THREAD

**Issue by Fiocher** [37385/SecureExplosion#3]
想要1.20.1的..

**Comment by SnowNF** [comment]
Forge 1.20 当时看了一下，和1.19的API有些变更，做是可以，就是配置文件以及效果(behavior)会有部分变化。

**Comment by SnowNF** [comment]
如果实在想要的话我可以再更新一下。

**Comment by Fiocher** [comment]
> 如果实在想要的话我可以再更新一下。

啊..没关系，很花时间就算了，已找到类似模组做替代
