### ISSUE TITLE
Fabric 1.21.1版本，该mod会导致旋风人的风弹伤害变为爆炸伤害

### ISSUE THREAD

**Issue by 2009zero** [37385/SecureExplosion#6]
基本信息：
在Fabric 1.21.1版本测试，被旋风人的风弹击中之后会造成爆炸伤害（2次就可以击杀穿无附魔全套下界合金套的玩家），在死亡界面显示的也是“被旋风人炸死了”。但在原版当中，风弹造成的应当为弹射物伤害且伤害仅为1点，被风弹打中杀死显示的死亡界面也为“被旋风人杀死了”。

重现过程：
加载该mod，并用刷怪蛋生成一只旋风人，切换到生存模式，由于风弹造成的是爆炸伤害，如果不穿装备被风弹击中，会直接死亡，显示被旋风人“炸死了”。

期望效果：
如同原版一样，风弹仅应当造成1点伤害。

加载mod后的效果（装备全套无附魔下界合金套进行测试）：
![2024-10-10_21 29 06](https://github.com/user-attachments/assets/f2d5d508-afb7-4c08-a262-7f5789894173)
原版效果：
![2024-10-10_21 27 54](https://github.com/user-attachments/assets/deb5fc5c-d068-41a1-80f9-0bfc62eec7cd)

**Comment by SnowNF** [comment]
https://www.mcmod.cn/download/3716.html

再试一下 `SecureExplosion-fabric-1.21.1-1.0.1.jar` 呢
